# Generated by Django 3.0.8 on 2020-08-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200807_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
